version: '3.8'

services:
  mongodb:
    image: mongo:5.0.25-focal
    container_name: "mongodb"
    ports:
      - 27070:27017
    volumes:
      - mongodb_data:/data/db

  users:
    build: .
    restart: always
    ports:
      - 8280:8280
    depends_on:
      - mongodb

volumes:
  mongodb_data: